"""Enhanced API routes (v1) showcasing svc-infra features.

Note: CRUD endpoints for Project and Task models are auto-generated by svc-infra
at /_sql/projects and /_sql/tasks. See main.py for SqlResource configuration.
"""

from datetime import datetime

from fastapi import Depends
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession
from svc_infra_template.db.models import Project, Task
from svc_infra_template.settings import settings

from svc_infra.api.fastapi.db.sql.session import SqlSessionDep
from svc_infra.api.fastapi.dual.public import public_router

router = public_router()


@router.get("/ping")
async def ping():
    """Health check endpoint."""
    return {
        "message": "pong",
        "service": "svc-infra-template",
        "version": "0.2.0",
    }


@router.get("/status")
async def status():
    """Detailed status endpoint with feature information."""
    return {
        "status": "healthy",
        "service": "svc-infra-template",
        "version": "0.2.0",
        "environment": settings.app_env,
        "features": {
            "database": settings.database_configured,
            "cache": settings.cache_configured,
            "metrics": settings.metrics_enabled,
            "webhooks": settings.webhooks_enabled,
            "payments": settings.payment_provider,
            "rate_limiting": settings.rate_limit_enabled,
            "idempotency": settings.idempotency_enabled,
        },
    }


@router.get("/features")
async def list_features():
    """List all available features and their configuration."""
    return {
        "service": "svc-infra-template",
        "version": "0.2.0",
        "features": {
            "core": {
                "versioned_api": True,
                "health_checks": True,
                "request_id": True,
                "exception_handling": True,
            },
            "database": {
                "enabled": settings.database_configured,
                "crud_endpoints": "/_sql/projects and /_sql/tasks (auto-generated)",
            },
            "cache": {
                "enabled": settings.cache_configured,
            },
            "observability": {
                "metrics": settings.metrics_enabled,
                "metrics_path": settings.metrics_path if settings.metrics_enabled else None,
            },
            "security": {
                "rate_limiting": settings.rate_limit_enabled,
                "idempotency": settings.idempotency_enabled,
                "cors": settings.cors_enabled,
            },
            "integrations": {
                "payments": settings.payment_provider,
                "webhooks": settings.webhooks_enabled,
            },
            "operations": {
                "maintenance_mode": settings.maintenance_mode,
                "admin": settings.admin_enabled,
                "jobs": settings.jobs_enabled,
            },
        },
        "documentation": {
            "openapi": "/openapi.json",
            "swagger_ui": "/docs",
            "redoc": "/redoc",
        },
    }


# =============================================================================
# Statistics & Aggregations
# Custom endpoint demonstrating complex queries
# =============================================================================


@router.get(
    "/stats/summary",
    summary="Get statistics summary",
    description="Get overall statistics about projects and tasks",
)
async def get_stats_summary(session: AsyncSession = Depends(SqlSessionDep)):
    """Get statistics summary."""
    if not settings.database_configured:
        return {
            "error": "Database is not configured. Set SQL_URL in .env to enable.",
            "projects": {"active": 0},
            "tasks": {"total": 0},
        }

    # Count active projects
    projects_result = await session.execute(
        select(Project).where(Project.deleted_at.is_(None), Project.is_active.is_(True))
    )
    active_projects = len(projects_result.scalars().all())

    # Count tasks by status
    tasks_result = await session.execute(select(Task))
    all_tasks = tasks_result.scalars().all()

    task_stats = {
        "total": len(all_tasks),
        "pending": sum(1 for t in all_tasks if t.status == "pending"),
        "in_progress": sum(1 for t in all_tasks if t.status == "in_progress"),
        "completed": sum(1 for t in all_tasks if t.status == "completed"),
        "cancelled": sum(1 for t in all_tasks if t.status == "cancelled"),
    }

    return {
        "projects": {
            "active": active_projects,
        },
        "tasks": task_stats,
        "timestamp": datetime.utcnow().isoformat(),
    }
