"""Initial migration - create user tables

Revision ID: 2a02f37f00e0
Revises: 
Create Date: 2025-09-07 13:36:12.388958
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a02f37f00e0'
down_revision = None
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

