{
 "title": "HTTP",
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "job", "query": "label_values(job)" },
   {
    "name": "instance",
    "query": "label_values(http_server_requests_total, instance)"
   },
   {
    "name": "method",
    "query": "label_values(http_server_requests_total, method)"
   }
  ]
 },
 "panels": [
  {
   "title": "RPS by Route",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (route) (rate(http_server_requests_total{job=~\"$job\",instance=~\"$instance\",method=~\"$method\",route!=\"\"}[$__rate_interval]))",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "Errors by Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by (code) (rate(http_server_requests_total{job=~\"$job\",instance=~\"$instance\",code!~\"2..|3..\"}[$__rate_interval]))",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "p95 Latency by Route (s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (route, le) (rate(http_server_request_duration_seconds_bucket{job=~\"$job\",instance=~\"$instance\",route!=\"\"}[$__rate_interval])))",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "Latency Histogram (all routes)",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by (le) (rate(http_server_request_duration_seconds_bucket{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Top Error Routes (5xx then 4xx)",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "topk(10, sum by (route) (rate(http_server_requests_total{code=~\"5..\",route!=\"\"}[$__rate_interval])))",
     "legendFormat": "5xx {{route}}"
    },
    {
     "expr": "topk(10, sum by (route) (rate(http_server_requests_total{code=~\"4..\",route!=\"\"}[$__rate_interval])))",
     "legendFormat": "4xx {{route}}"
    }
   ]
  }
 ]
}