name: Auto publish to PyPI on main

on:
  push:
    branches: [ main ]

concurrency:
  group: publish-pypi
  cancel-in-progress: false

jobs:
  release:
    # avoid an infinite loop when the bot pushes the version bump commit
    if: ${{ github.actor != 'github-actions[bot]' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write   # for committing/tagging version bumps
      id-token: write   # REQUIRED for PyPI Trusted Publisher (OIDC)

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # This ensures the requested Poetry version is actually installed & on PATH
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: "2.0.1"
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Show Poetry version
        run: poetry --version

      # Make sure the lock is good: Poetry 2 uses --check, Poetry 1 uses --no-update
      - name: Verify lockfile matches pyproject
        shell: bash
        run: |
          set -euo pipefail
          VER=$(poetry --version | awk '{print $3}')
          MAJOR=${VER%%.*}
          if [[ "$MAJOR" -ge 2 ]]; then
            poetry lock --check
          else
            poetry lock --no-update
          fi

      - name: Install deps (no dev)
        run: poetry install --no-root --only main --sync

      - name: Configure git identity
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      # Bump patch version on every push to main
      - name: Bump patch version
        id: bump
        run: |
          poetry version patch
          NEW_VER=$(poetry version -s)
          echo "new_version=$NEW_VER" >> "$GITHUB_OUTPUT"

      - name: Commit version bump
        run: |
          NEW_VER="${{ steps.bump.outputs.new_version }}"
          git add pyproject.toml poetry.lock || true
          git commit -m "ci: release v${NEW_VER}" || echo "No changes to commit"
          git tag "v${NEW_VER}" || echo "Tag exists; continuing"
          git push || true
          git push --tags || true

      - name: Build distributions
        run: poetry build

      # OIDC/Trusted Publisher to PyPI (no API token)
      - name: Publish to PyPI via OIDC
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist